spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${AUTH_DB_AUTO_UPDATE:none}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  host: ${AUTH_HOST}
  port: ${AUTH_PORT}

kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  topic:
    user-created: ${KAFKA_TOPIC_USER_CREATED}

secret:
  access-token-key: ${SECRET_ACCESS_TOKEN_KEY}
  refresh-token-key: ${SECRET_REFRESH_TOKEN_KEY}
  access-token-ttl: ${SECRET_ACCESS_TOKEN_TTL}
  refresh-token-ttl: ${SECRET_REFRESH_TOKEN_TTL}
