server:
  host: ${USERS_HOST}
  port: ${USERS_PORT}

spring:
  application:
    name: users-service

  datasource:
    url: jdbc:postgresql://${USERS_DB_HOST}:${USERS_DB_PORT}/${USERS_DB_NAME}
    username: ${USERS_DB_USERNAME:postgres}
    password: ${USERS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
    redis:
      time-to-live: ${USERS_CACHE_TTL}

  redis:
    host: ${USERS_REDIS_HOST}
    port: ${USERS_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  topic:
    user-events: ${KAFKA_TOPIC_USER_CREATED}
    avatar-update: ${KAFKA_TOPIC_AVATAR_UPDATED}
  group-id:
    users-service: ${KAFKA_USERS_GROUP}

secret:
  access-token-key: ${SECRET_ACCESS_TOKEN_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    com:
      fasterxml:
        jackson:
          databind=DEBUG:
    org:
      springframework:
        data:
          redis=DEBUG: