spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/v1/auth/**
            - id: users-service
              uri: ${USERS_SERVICE_URL}
              predicates:
                - Path=/api/v1/users/**
            - id: media-service
              uri: ${MEDIA_SERVICE_URL}
              predicates:
                - Path=/api/v1/media/**

server:
  port: ${PORT}
