spring:
  application:
    name: search-service

search-engine:
  config:
    host: ${SEARCH_ENGINE_HOST}
    port: ${SEARCH_ENGINE_PORT}

kafka:
  config:
    bootstrap-servers: ${KAFKA_SERVER}
  group-id:
    search-group: ${KAFKA_SEARCH_GROUP}
  topic:
    users-updated: ${KAFKA_TOPIC_USER_UPDATED}
    users-created: ${KAFKA_TOPIC_USER_CREATED}