spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://${SEARCH_ENGINE_HOST}:${SEARCH_ENGINE_PORT}
    connection-timeout: 1000
    read-timeout: 3000

server:
  host: ${SEARCH_HOST}
  port: ${SEARCH_PORT}

search-engine:
  config:
    host: ${SEARCH_ENGINE_HOST}
    port: ${SEARCH_ENGINE_PORT}

kafka:
  config:
    bootstrap-servers: ${KAFKA_SERVER}
  group-id:
    search-group: ${KAFKA_SEARCH_GROUP}
  topic:
    users-updated: ${KAFKA_TOPIC_USER_UPDATED}
    users-created: ${KAFKA_TOPIC_USER_CREATED}

logging:
  level:
    root: DEBUG