spring:
  application:
    name: media-service

server:
  host: ${MEDIA_HOST}
  port: ${MEDIA_PORT}

s3:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  internalEndpoint: ${S3_INTERNAL_ENDPOINT}
  publicEndpoint: ${S3_PUBLIC_ENDPOINT}
  region: ${S3_REGION}
  avatarsBucketName: ${AVATARS_BUCKET}
  imagesBucketName: ${IMAGES_BUCKET}
  presignDurationSeconds: ${PRESIGN_DURATION_SECONDS}

secret:
  access-token-key: ${ACCESS_TOKEN_KEY}

kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  topic:
    avatar-update: ${KAFKA_TOPIC_AVATAR_UPDATED}
