spring:
  application:
    name: media-service

server:
  host: ${MEDIA_HOST}
  port: ${MEDIA_PORT}

s3:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  avatarsBucketName: ${AVATARS_BUCKET}
  presignDurationSeconds: ${PRESIGN_DURATION_SECONDS}
  basePublicUrl: ${S3_BASE_PUBLIC_URL}

secret:
  access-token-key: ${ACCESS_TOKEN_KEN}

kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  topic:
    avatar-update: ${KAFKA_TOPIC_AVATAR_UPDATED}
