server:
  host: ${POSTS_HOST}
  port: ${POSTS_PORT}

spring:
  application:
    name: posts-service

  datasource:
    url: jdbc:postgresql://${POSTS_DB_HOST}:${POSTS_DB_PORT}/${POSTS_DB_NAME}
    username: ${POSTS_DB_USERNAME}
    password: ${POSTS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${AUTH_DB_AUTO_UPDATE:none}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  topic:
    user-removed: ${KAFKA_TOPIC_USER_REMOVED}
  group-id:
    posts-group: ${KAFKA_POSTS_GROUP}